_wandb:
    value:
        cli_version: 0.25.1
        e:
            9k33dwvfb582fe6omr91o8apeftkalz7:
                args:
                    - data/commit_pairs_production
                    - --model
                    - Qwen/Qwen3-VL-235B-A22B-Instruct
                    - --batch-size
                    - "1"
                    - --max-samples
                    - "100"
                    - --group-size
                    - "2"
                    - --max-tokens
                    - "8192"
                    - --no-diagrams
                    - --log-path
                    - output/grpo_235b_constrained
                codePath: scripts\train_grpo_tinker.py
                codePathLocal: scripts\train_grpo_tinker.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.7"
                disk:
                    /:
                        total: "254441230336"
                        used: "247844995072"
                email: k_power7@hotmail.com
                executable: C:\Users\Local User\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: e36b3bb062e53a975fa388efa16ec9af8c43e146
                    remote: https://github.com/andreajf94/Multimodal.git
                gpu: Quadro M1000M
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Maxwell
                      cudaCores: 512
                      memoryTotal: "2147483648"
                      name: Quadro M1000M
                      uuid: GPU-ecc2af37-a918-2916-101b-92a7635ed926
                host: KP
                memory:
                    total: "17054658560"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Local User\Documents\GitHub\Multimodal\scripts\train_grpo_tinker.py
                python: CPython 3.12.2
                root: C:\Users\Local User\Documents\GitHub\Multimodal
                startedAt: "2026-03-16T07:45:15.873672Z"
                writerId: 9k33dwvfb582fe6omr91o8apeftkalz7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 16
                - 61
            "4": 3.12.2
            "5": 0.25.1
            "6": 4.37.2
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch_size:
    value: 1
group_size:
    value: 2
learning_rate:
    value: 1e-05
lora_rank:
    value: 64
max_tokens:
    value: 8192
model_name:
    value: Qwen/Qwen3-VL-235B-A22B-Instruct
num_epochs:
    value: 1
use_diagrams:
    value: false
use_llm_judge:
    value: true
